"$schema" = 'https://starship.rs/config-schema.json'

format = """
[â•­â”€î‚²](mauve)\
$os\
[î‚° ](bg:red fg:mauve)\
$username\
$hostname\
[î‚°](bg:peach fg:red)\
[ ï¼ ](bg:peach fg:black)\
$directory\
[ ](bg:peach)\
[î‚°](bg:yellow fg:peach)\
$git_branch\
$git_status\
$git_commit\
$git_metrics\
[î‚°](fg:yellow bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[î‚°](fg:green bg:sapphire)\
$conda\
[î‚°](fg:sapphire bg:lavender)\
[î‚°](fg:lavender)\
$fill\
[î‚²](fg:red)\
$status\
[î‚²](fg:mauve bg:red)\
$cmd_duration\
[î‚²](bg:mauve fg:lavender)\
$time\
[î‚°](bg:mauve fg:lavender)\
[î‚°â”€â•®](fg:mauve)\
$line_break\
[â•°â”€](mauve)\
$character\
"""

right_format = """
[â”€â•¯](mauve)\
"""

[os]
format = "[ $symbol]($style)()"
style = "bg:mauve fg:crust"
disabled = false

[os.symbols]
AIX = "AIX "
Alpaquita = "\uf26a " # \uf26a ï‰ª # \ue3a5\ue390 î¥î
AlmaLinux = "\uf31d " # ïŒ
Alpine = "\uf300 " # "ïŒ€"
Amazon = "\uf270 " # "ï‰°"
Android = "\ue70e " # "îœ"
Arch = "\uf303 " # "ïŒƒ"
Artix = "\uf31f " # ïŒŸ
CentOS = "\uf304 " # "ïŒ„"
Debian = "\uf306 " # "ïŒ†"
DragonFly = "\ueef8 " # î»¸  î† ğŸ‰
Emscripten = "\u26A1 " # âš¡
EndeavourOS = "\uf322 " # "ïŒ¢" # ï†—
Fedora = "\uf30a " # "ïŒŠ"
FreeBSD = "\uf30c " # "ïŒŒ"
Garuda = "\uf337 " # "ïŒ·"
Gentoo = "\uf30d " # "ïŒ"
HardenedBSD = "\uf132 " # ï„²
Illumos = "\uf326 " # "ğŸ¦"
Kali = "\uf327 " # ïŒ§
Linux = "\uf17c " # "ï…¼"
Mabox = "\uf1b2 " # ï†² ğŸ“¦
Macos = "\uf302 " # "ïŒ‚"
Manjaro = "\uf312 " # "ïŒ’"
Mariner = "\ue7ae " # \ue7ae î®
MidnightBSD = "\ue3e0 " # ğŸŒ˜
Mint = "\uf30e " # "ïŒ"
NetBSD = "\u2691 " # âš‘
NixOS = "\uf313 " # "ïŒ“"
OpenBSD = "\uf328 " # "ïŒ¨"
OpenCloudOS = "\uf0c2 " # ïƒ‚
openEuler = "\u2208 " # \u2208 âˆˆ
openSUSE = "\uf314 " # "ïŒ”"
OracleLinux = "\u213A " # \u213A â„º # âŠ‚âŠƒ \u2282\u2283
Pop = "\uf32a " # "ïŒª"
Raspbian = "\uf315 " # "ïŒ•"
Redhat = "\uf316 " # "ïŒ–" # ó±„›
RedHatEnterprise = "\uf316 " # "ïŒ–" # ó±„›
RockyLinux = "\uf32b " # ïŒ«
Redox = "\uf331 " # ïŒ±  ó°º•
Solus = "\uf32d " # "ïŒ­" # "ï…¼ "
SUSE = "\uef6d " # "ïŒ”"
Ubuntu = "\uf31b " # "ïŒ›"
Ultramarine = "ó±™³ " # ğŸ”·
Unknown = "\uf108 " # "ï„ˆ"
Void = "\uf32e " # ïŒ® îŠ™
Windows = "\uf17a " # "îœ"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust bold"
format = '[$user]($style)'

[hostname]
format = '[@$hostname ](bg:red fg:crust)'
ssh_only = false
# ssh_symbol = "@" # \ue36e 'î®' # 'ï…½â‡’' # 'ï£· ' # 'ï¬â‡’'
# trim_at = '.companyname.com'
disabled = false

[fill]
symbol = ' '
style = 'bold subtext1'

[directory]
style = "bg:peach fg:crust"
format = '[$path]($style)[$read_only]($read_only_style)'
truncation_length = 3
truncation_symbol = "~/"
read_only = ' ğŸ”’'
read_only_style = 'bg:peach'

[git_branch]
symbol = "ï˜"
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_commit]
format = '[\($hash$tag\)]($style)[ ]()'
style = 'bg:yellow'
commit_hash_length = 8
tag_symbol = " \uf412 " # \uf412 ' ï’ ' # ' ï€« ''
tag_disabled = false
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\]]($deleted_style)[ ](bg:yellow)'
added_style = 'bg:yellow fg:crust'
deleted_style = 'bg:yellow fg:crust'
disabled = false

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = "î˜ "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = "î¨"
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = "î˜§"
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = "î‰– "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = "î˜†"
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = " ï„Œ "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[status]
format = "[$symbol $status $hex_status( \uf0a2 $signal_number-$signal_name)]($style)" # \uf0a2 ï–› , \ueaa2
#format = "[$symbol $status ]($style)" # \uf0a2 ï–› , \ueaa2
style = 'fg:crust bg:red'
success_symbol = '' # 'âœ”'
symbol = " \u2717" # \u2717 \uf467 \uebde î¯ âœ˜
disabled = false
map_symbol = false

[time]
format = "[ $time ï€—]($style)"
style = 'bg:lavender fg:crust'
disabled = false # set to 'false', if you want to see the time

[cmd_duration]
show_milliseconds = true
format = "[ took [$duration ](bold fg:crust bg:mauve)](fg:crust bg:mauve)"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[character]
disabled = false
success_symbol = '[â¯](bold fg:green)'
error_symbol = '[âœ˜](bold fg:red)'
vimcmd_symbol = '[â®](bold fg:green)'
vimcmd_replace_one_symbol = '[â®](bold fg:lavender)'
vimcmd_replace_symbol = '[â®](bold fg:lavender)'
vimcmd_visual_symbol = '[â®](bold fg:yellow)'